import CoreGraphics
import ForgeCore

/// Normalized bounding boxes of each muscle mask, per side. Generated by scripts/import-muscle-figure.py.
enum MuscleFigureRegions {
  static let aspect: CGFloat = 495.0 / 960.0
  static let front: [Muscle: CGRect] = [
    .chest: CGRect(x: 0.2929, y: 0.1906, width: 0.4121, height: 0.1021),
    .frontDelts: CGRect(x: 0.2263, y: 0.1781, width: 0.5455, height: 0.0854),
    .sideDelts: CGRect(x: 0.2242, y: 0.2281, width: 0.5495, height: 0.1021),
    .biceps: CGRect(x: 0.2121, y: 0.2438, width: 0.5737, height: 0.1031),
    .forearms: CGRect(x: 0.1414, y: 0.3229, width: 0.7152, height: 0.1583),
    .abs: CGRect(x: 0.4141, y: 0.2792, width: 0.1717, height: 0.2281),
    .quads: CGRect(x: 0.2990, y: 0.4615, width: 0.4020, height: 0.2312),
  ]
  static let back: [Muscle: CGRect] = [
    .back: CGRect(x: 0.3212, y: 0.1104, width: 0.3576, height: 0.3135),
    .rearDelts: CGRect(x: 0.2323, y: 0.1875, width: 0.5354, height: 0.0833),
    .sideDelts: CGRect(x: 0.2970, y: 0.2104, width: 0.4040, height: 0.0719),
    .triceps: CGRect(x: 0.2141, y: 0.2406, width: 0.5717, height: 0.1323),
    .glutes: CGRect(x: 0.3434, y: 0.4208, width: 0.3111, height: 0.1250),
    .hamstrings: CGRect(x: 0.3253, y: 0.5365, width: 0.3475, height: 0.1948),
    .calves: CGRect(x: 0.3131, y: 0.6938, width: 0.3737, height: 0.2490),
  ]
}
