import SwiftUI
import UIKit
import ForgeCore

/// The A4 report page. Rendered into the PDF and, scaled down, as the share sheet's preview.
struct ReportPage: View {
  let content: ReportContent

  var body: some View {
    VStack(alignment: .leading, spacing: 18) {
      Text(content.title)
        .forge(22, .bold, tracking: -0.8)
      Text(content.rangeText)
        .forge(12, .medium)
        .foregroundStyle(Theme.textSecondary)

      if let workouts = content.workouts {
        block("Workouts") {
          VStack(alignment: .leading, spacing: 12) {
            Text("\(workouts.sessions) sessions · \(workouts.volumeText) total volume")
              .forge(13, .medium)
              .monospacedDigit()
            weekBars(workouts.weeks)
          }
        }
      }
      if let changes = content.changes { block("Program changes") { lines(changes) } }
      if let records = content.records { block("Records") { lines(records) } }
      if let bodyStats = content.bodyStats { block("Body stats") { lines(bodyStats) } }
      if let notes = content.notes { block("Notes") { lines(notes) } }
      if let photos = content.photos {
        block("Progress photos") {
          Text(photos.text)
            .forge(13, .medium)
            .fixedSize(horizontal: false, vertical: true)
        }
      }
      if content.withheldNotes || content.withheldPhotos { withheld }

      Spacer(minLength: 0)
      Text("Generated by Regulift")
        .forge(11, .medium)
        .foregroundStyle(Theme.textTertiary)
    }
    .foregroundStyle(Theme.text)
    .frame(width: 523, alignment: .leading)
    .environment(\.colorScheme, .light)
  }

  private func block(_ heading: LocalizedStringKey, @ViewBuilder body: () -> some View) -> some View {
    VStack(alignment: .leading, spacing: 8) {
      Text(heading).forge(17, .semibold)
      body()
    }
  }

  private func lines(_ lines: [ReportContent.Line]) -> some View {
    VStack(alignment: .leading, spacing: 6) {
      ForEach(Array(lines.enumerated()), id: \.offset) { _, line in
        HStack(alignment: .firstTextBaseline, spacing: 8) {
          Text(line.text)
            .forge(13, .medium)
            .fixedSize(horizontal: false, vertical: true)
          if let date = line.date {
            Spacer(minLength: 8)
            Text(shortDate(date))
              .forge(11, .medium)
              .foregroundStyle(Theme.textSecondary)
          }
        }
      }
    }
  }

  private func weekBars(_ weeks: [ReportContent.WeekBar]) -> some View {
    let peak = max(weeks.map(\.volumeKg).max() ?? 0, 0)
    return VStack(alignment: .leading, spacing: 6) {
      ForEach(weeks, id: \.start) { week in
        HStack(spacing: 10) {
          Text(shortDate(week.start))
            .forge(11, .medium)
            .foregroundStyle(Theme.textSecondary)
            .lineLimit(1)
            .minimumScaleFactor(0.7)
            .frame(width: 48, alignment: .leading)
          GeometryReader { geo in
            ZStack(alignment: .leading) {
              Capsule().fill(Theme.track)
              Capsule()
                .fill(week.isCurrent ? Theme.accent : Theme.accent.opacity(0.35))
                .frame(width: peak > 0 ? geo.size.width * week.volumeKg / peak : 0)
            }
          }
          .frame(height: 8)
        }
        .accessibilityElement(children: .combine)
      }
    }
  }

  /// Day-month, ordered the way the reader's locale writes it, like the range and photo lines.
  private func shortDate(_ date: Date) -> String {
    let formatter = DateFormatter()
    formatter.locale = L10n.locale
    formatter.setLocalizedDateFormatFromTemplate("dMMM")
    return formatter.string(from: date)
  }

  private var withheld: some View {
    HStack(spacing: 8) {
      Image(systemName: "lock.fill")
        .font(.system(size: 13, weight: .semibold))
        .foregroundStyle(Theme.textSecondary)
        .accessibilityHidden(true)
      Text(withheldText)
        .forge(13, .medium)
        .fixedSize(horizontal: false, vertical: true)
    }
    .padding(.horizontal, 12)
    .padding(.vertical, 10)
    .background(RoundedRectangle(cornerRadius: Theme.radiusChip, style: .continuous).fill(Theme.innerSurface))
    .overlay(
      RoundedRectangle(cornerRadius: Theme.radiusChip, style: .continuous)
        .strokeBorder(Theme.ring, lineWidth: 1))
  }

  /// The one line that names exactly what stayed private: notes, photos or both.
  private var withheldText: String {
    switch (content.withheldNotes, content.withheldPhotos) {
    case (true, false): return String(localized: "Notes not included", bundle: L10n.bundle)
    case (false, true): return String(localized: "Photos not included", bundle: L10n.bundle)
    default: return String(localized: "Notes and photos not included", bundle: L10n.bundle)
    }
  }
}

enum ReportPDF {
  /// One A4 page (595.2 × 841.8 pt), 36 pt margins, always the light scheme.
  @MainActor
  static func data(_ content: ReportContent) -> Data {
    let a4 = CGRect(x: 0, y: 0, width: 595.2, height: 841.8)
    let renderer = ImageRenderer(
      content: ReportPage(content: content).environment(\.locale, L10n.locale))
    return UIGraphicsPDFRenderer(bounds: a4).pdfData { pdf in
      pdf.beginPage()
      renderer.render(rasterizationScale: 1) { _, draw in
        guard let cg = UIGraphicsGetCurrentContext() else { return }
        cg.translateBy(x: 36, y: 36)
        draw(cg)
      }
    }
  }

  /// The entry point the app already uses: default options over a workouts-only source.
  @MainActor
  static func url(sessions: [WorkoutSession], profile: UserProfile?) -> URL {
    ProgressExport.fileURL(
      ProgressExportOptions(),
      source: ProgressExportSource(
        sessions: sessions, decisions: [], measurements: [], notes: [], photos: [],
        profile: profile))
  }
}
