import SwiftUI
import UIKit
import ForgeCore

enum ReportPDF {
  @MainActor
  static func url(sessions: [WorkoutSession], profile: UserProfile?) -> URL {
    let usesLb = profile?.usesLb ?? false
    let completed = sessions.filter(\.completed).sorted { $0.date < $1.date }

    var bests: [String: Double] = [:]
    for s in completed {
      for set in s.sets {
        let e = Strength.epley(weightKg: set.weightKg, reps: set.reps)
        if e > bests[set.exerciseID] ?? 0 { bests[set.exerciseID] = e }
      }
    }
    let top = bests
      .compactMap { id, e in ExerciseDB.find(id).map { (name: $0.name, e1rm: e) } }
      .sorted { $0.e1rm > $1.e1rm }
      .prefix(5).map { $0 }

    let cal = Calendar(identifier: .iso8601)
    let thisWeek = cal.dateInterval(of: .weekOfYear, for: .now)?.start ?? .now
    let weeks: [(start: Date, sets: Int)] = (0..<8).compactMap { i in
      guard let start = cal.date(byAdding: .weekOfYear, value: i - 7, to: thisWeek) else { return nil }
      let sets = completed
        .filter { cal.dateInterval(of: .weekOfYear, for: $0.date)?.start == start }
        .flatMap(\.sets)
        .filter { $0.rpe >= 6 }
        .count
      return (start: start, sets: sets)
    }

    let tonnage = completed.flatMap(\.sets).reduce(0.0) { $0 + $1.weightKg * Double($1.reps) }
    let content = ReportDocument(
      from: completed.first?.date,
      to: completed.last?.date,
      sessions: completed.count,
      tonnage: UnitFormat.weight(tonnage, usesLb: usesLb),
      top: top,
      weeks: weeks,
      unit: usesLb ? "lb" : "kg")
      .environment(\.colorScheme, .light)

    let a4 = CGRect(x: 0, y: 0, width: 595.2, height: 841.8)
    let renderer = ImageRenderer(content: content)
    let data = UIGraphicsPDFRenderer(bounds: a4).pdfData { pdf in
      pdf.beginPage()
      renderer.render(rasterizationScale: 1) { _, draw in
        guard let cg = UIGraphicsGetCurrentContext() else { return }
        cg.translateBy(x: 36, y: 36)
        draw(cg)
      }
    }
    let url = FileManager.default.temporaryDirectory.appendingPathComponent("forge-report.pdf")
    try? data.write(to: url)
    return url
  }
}

private struct ReportDocument: View {
  let from: Date?
  let to: Date?
  let sessions: Int
  let tonnage: String
  let top: [(name: String, e1rm: Double)]
  let weeks: [(start: Date, sets: Int)]
  let unit: String

  var body: some View {
    VStack(alignment: .leading, spacing: 14) {
      Text("REGULIFT — Training Report")
        .forge(22, .bold, tracking: -0.8)
      Text(rangeText)
        .forge(12, .medium)
        .foregroundStyle(Theme.textSecondary)
      Divider()
      Text("\(sessions) sessions · \(tonnage) total volume")
        .forge(15, .medium)
      Divider()
      Text("Top lifts (e1RM)").forge(17, .semibold)
      ForEach(top, id: \.name) { lift in
        Text("\(lift.name) — \(Int(UnitFormat.plain(lift.e1rm, usesLb: unit == "lb").rounded())) \(unit)")
          .forge(13, .medium)
          .monospacedDigit()
      }
      Divider()
      Text("Weekly sets").forge(17, .semibold)
      ForEach(weeks, id: \.start) { week in
        Text("\(week.start.formatted(.dateTime.month(.wide).day())) — \(week.sets) sets")
          .forge(13, .medium)
          .monospacedDigit()
      }
      Spacer(minLength: 0)
      Text("Generated by Regulift")
        .forge(11, .medium)
        .foregroundStyle(Theme.textTertiary)
    }
    .foregroundColor(Theme.text)
    .frame(width: 523, alignment: .leading)
  }

  private var rangeText: String {
    switch (from, to) {
    case let (f?, t?):
      return "\(f.formatted(.dateTime.month(.wide).day().year())) – \(t.formatted(.dateTime.month(.wide).day().year()))"
    default:
      return "No completed sessions yet"
    }
  }
}
