public enum ExerciseDB {
  // ponytail: 83 exercises now, PRD wants 300+; extend the literal when beta users ask for missing lifts.
  public static let all: [Exercise] = [
    Exercise(id: "barbell_bench", name: "Barbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "db_bench_neutral", name: "Neutral-Grip Dumbbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "incline_db_press", name: "Incline Dumbbell Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "incline_barbell_press", name: "Incline Barbell Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "machine_chest_press", name: "Machine Chest Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "machine_incline_press", name: "Machine Incline Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "dips", name: "Dips", pattern: .verticalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "push_up", name: "Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "cable_fly", name: "Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "db_fly", name: "Dumbbell Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "pec_deck", name: "Pec Deck", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "bent_row", name: "Barbell Bent-Over Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "pendlay_row", name: "Pendlay Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "chest_supported_row", name: "Chest-Supported Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "single_arm_db_row", name: "Single-Arm Dumbbell Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "seated_cable_row", name: "Seated Cable Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .cable),
    Exercise(id: "machine_row", name: "Machine Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "inverted_row", name: "Inverted Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "band_row", name: "Band Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bands),
    Exercise(id: "pull_up", name: "Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "chin_up", name: "Chin-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "lat_pulldown", name: "Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "straight_arm_pulldown", name: "Straight-Arm Pulldown", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "back_squat", name: "Back Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "front_squat", name: "Front Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "goblet_squat", name: "Goblet Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "leg_press", name: "Leg Press", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "hack_squat", name: "Hack Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "lunge", name: "Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .bodyweight),
    Exercise(id: "bulgarian_split_squat", name: "Bulgarian Split Squat", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "leg_extension", name: "Leg Extension", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "sissy_squat", name: "Sissy Squat", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "band_leg_extension", name: "Band Leg Extension", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "deadlift", name: "Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "romanian_deadlift", name: "Romanian Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "good_morning", name: "Good Morning", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "leg_curl", name: "Lying Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "seated_leg_curl", name: "Seated Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "nordic_curl", name: "Nordic Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "glute_ham_raise", name: "Glute-Ham Raise", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "single_leg_rdl", name: "Single-Leg Romanian Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "hip_thrust", name: "Barbell Hip Thrust", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .barbell),
    Exercise(id: "sumo_deadlift", name: "Sumo Deadlift", pattern: .hinge, primary: .glutes, synergists: [.hamstrings, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "cable_pull_through", name: "Cable Pull-Through", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .cable),
    Exercise(id: "glute_bridge", name: "Glute Bridge", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .bodyweight),
    Exercise(id: "cable_kickback", name: "Cable Glute Kickback", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "overhead_press", name: "Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "seated_db_press", name: "Seated Dumbbell Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "arnold_press", name: "Arnold Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "landmine_press", name: "Landmine Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .chest], isCompound: true, equipment: .barbell),
    Exercise(id: "machine_shoulder_press", name: "Machine Shoulder Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .machine),
    Exercise(id: "band_ohp", name: "Band Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .bands),
    Exercise(id: "lateral_raise", name: "Dumbbell Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_lateral_raise", name: "Cable Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "machine_lateral_raise", name: "Machine Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "band_lateral_raise", name: "Band Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "face_pull", name: "Face Pull", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "rear_delt_fly", name: "Rear Delt Fly", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "reverse_pec_deck", name: "Reverse Pec Deck", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "band_pull_apart", name: "Band Pull-Apart", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "close_grip_bench", name: "Close-Grip Bench Press", pattern: .horizontalPush, primary: .triceps, synergists: [.chest, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "tricep_pushdown", name: "Tricep Pushdown", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "skullcrusher", name: "Skullcrusher", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "overhead_db_extension", name: "Overhead Dumbbell Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "bodyweight_triceps_extension", name: "Bodyweight Triceps Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "barbell_curl", name: "Barbell Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "hammer_curl", name: "Hammer Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "incline_db_curl", name: "Incline Dumbbell Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "spider_curl", name: "Spider Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_curl", name: "Cable Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_curl", name: "Band Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "standing_calf_raise", name: "Standing Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "seated_calf_raise", name: "Seated Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "donkey_calf_raise", name: "Donkey Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "db_calf_raise", name: "Dumbbell Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_crunch", name: "Cable Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "hanging_leg_raise", name: "Hanging Leg Raise", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "machine_crunch", name: "Machine Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "cable_woodchop", name: "Cable Woodchop", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_pallof_press", name: "Band Pallof Press", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "wrist_curl", name: "Wrist Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "reverse_curl", name: "Reverse Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "farmer_walk", name: "Farmer's Walk", pattern: .carry, primary: .forearms, synergists: [.back], isCompound: true, equipment: .dumbbell),
  ]

  public static func find(_ id: String) -> Exercise? {
    all.first { $0.id == id }
  }

  public static func matching(equipment: Set<Equipment>) -> [Exercise] {
    all.filter { equipment.contains($0.equipment) }
  }
}
