#!/usr/bin/env python3.13
"""Imports the illustrated muscle figure into the Forge asset catalog.

Usage: python3.13 scripts/import-muscle-figure.py /tmp/forge-art/figure/out
Copies figure PNGs into App/Forge/Assets.xcassets/MuscleFigure as imagesets
and regenerates App/Forge/MuscleFigureRegions.swift from regions.json.
Idempotent.
"""
import json
import shutil
import sys
from pathlib import Path

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/forge-art/figure/out")
ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "App/Forge/Assets.xcassets/MuscleFigure"

INFO = {"info": {"author": "xcode", "version": 1}}


def write_json(path, payload):
  path.write_text(json.dumps(payload) + "\n")


def import_imagesets():
  ASSETS.mkdir(parents=True, exist_ok=True)
  write_json(ASSETS / "Contents.json", INFO)
  for png in sorted(SRC.glob("*.png")):
    imageset = ASSETS / f"{png.stem}.imageset"
    imageset.mkdir(exist_ok=True)
    shutil.copyfile(png, imageset / png.name)
    write_json(imageset / "Contents.json", {
      "images": [{"filename": png.name, "idiom": "universal"}],
      "info": {"author": "xcode", "version": 1},
    })
  return len(list(SRC.glob("*.png")))


def region_lines(regions):
  return "\n".join(
    f"    .{muscle}: CGRect(x: {x:.4f}, y: {y:.4f}, width: {w:.4f}, height: {h:.4f}),"
    for muscle, (x, y, w, h) in regions.items())


def write_regions_swift():
  data = json.loads((SRC / "regions.json").read_text())
  width, height = data["size"]
  regions = data["regions"]
  swift = f"""import CoreGraphics
import ForgeCore

/// Normalized bounding boxes of each muscle mask, per side. Generated by scripts/import-muscle-figure.py.
enum MuscleFigureRegions {{
  static let aspect: CGFloat = {width}.0 / {height}.0
  static let front: [Muscle: CGRect] = [
{region_lines(regions["front"])}
  ]
  static let back: [Muscle: CGRect] = [
{region_lines(regions["back"])}
  ]
}}
"""
  (ROOT / "App/Forge/MuscleFigureRegions.swift").write_text(swift)


if __name__ == "__main__":
  count = import_imagesets()
  write_regions_swift()
  print(f"Imported {count} imagesets and MuscleFigureRegions.swift from {SRC}")
