import Foundation

public enum ExerciseDB {
  /// Owner sets a CDN base; videoURL stays nil until then.
  public static var videoBaseURL: URL? = nil

  // ponytail: DB is now 300+ exercises, satisfying PRD §11.
  public static let all: [Exercise] = [
    Exercise(id: "barbell_bench", name: "Barbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "db_bench_neutral", name: "Neutral-Grip Dumbbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "incline_db_press", name: "Incline Dumbbell Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "incline_barbell_press", name: "Incline Barbell Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "machine_chest_press", name: "Machine Chest Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "machine_incline_press", name: "Machine Incline Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "dips", name: "Dips", pattern: .verticalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "push_up", name: "Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "cable_fly", name: "Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "db_fly", name: "Dumbbell Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "pec_deck", name: "Pec Deck", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "bent_row", name: "Barbell Bent-Over Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "pendlay_row", name: "Pendlay Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "chest_supported_row", name: "Chest-Supported Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "single_arm_db_row", name: "Single-Arm Dumbbell Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "seated_cable_row", name: "Seated Cable Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .cable),
    Exercise(id: "machine_row", name: "Machine Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "inverted_row", name: "Inverted Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "band_row", name: "Band Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bands),
    Exercise(id: "pull_up", name: "Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "chin_up", name: "Chin-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "lat_pulldown", name: "Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "straight_arm_pulldown", name: "Straight-Arm Pulldown", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "back_squat", name: "Back Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "front_squat", name: "Front Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "goblet_squat", name: "Goblet Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "leg_press", name: "Leg Press", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "hack_squat", name: "Hack Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "lunge", name: "Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .bodyweight),
    Exercise(id: "bulgarian_split_squat", name: "Bulgarian Split Squat", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "leg_extension", name: "Leg Extension", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "sissy_squat", name: "Sissy Squat", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "band_leg_extension", name: "Band Leg Extension", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "deadlift", name: "Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "romanian_deadlift", name: "Romanian Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "good_morning", name: "Good Morning", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "leg_curl", name: "Lying Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "seated_leg_curl", name: "Seated Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "nordic_curl", name: "Nordic Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "glute_ham_raise", name: "Glute-Ham Raise", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "single_leg_rdl", name: "Single-Leg Romanian Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "hip_thrust", name: "Barbell Hip Thrust", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .barbell),
    Exercise(id: "sumo_deadlift", name: "Sumo Deadlift", pattern: .hinge, primary: .glutes, synergists: [.hamstrings, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "cable_pull_through", name: "Cable Pull-Through", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .cable),
    Exercise(id: "glute_bridge", name: "Glute Bridge", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .bodyweight),
    Exercise(id: "cable_kickback", name: "Cable Glute Kickback", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "overhead_press", name: "Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "seated_db_press", name: "Seated Dumbbell Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "arnold_press", name: "Arnold Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "landmine_press", name: "Landmine Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .chest], isCompound: true, equipment: .barbell),
    Exercise(id: "machine_shoulder_press", name: "Machine Shoulder Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .machine),
    Exercise(id: "band_ohp", name: "Band Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .bands),
    Exercise(id: "lateral_raise", name: "Dumbbell Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_lateral_raise", name: "Cable Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "machine_lateral_raise", name: "Machine Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "band_lateral_raise", name: "Band Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "face_pull", name: "Face Pull", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "rear_delt_fly", name: "Rear Delt Fly", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "reverse_pec_deck", name: "Reverse Pec Deck", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "band_pull_apart", name: "Band Pull-Apart", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "close_grip_bench", name: "Close-Grip Bench Press", pattern: .horizontalPush, primary: .triceps, synergists: [.chest, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "tricep_pushdown", name: "Tricep Pushdown", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "skullcrusher", name: "Skullcrusher", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "overhead_db_extension", name: "Overhead Dumbbell Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "bodyweight_triceps_extension", name: "Bodyweight Triceps Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "barbell_curl", name: "Barbell Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "hammer_curl", name: "Hammer Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "incline_db_curl", name: "Incline Dumbbell Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "spider_curl", name: "Spider Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_curl", name: "Cable Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_curl", name: "Band Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "standing_calf_raise", name: "Standing Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "seated_calf_raise", name: "Seated Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "donkey_calf_raise", name: "Donkey Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "db_calf_raise", name: "Dumbbell Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_crunch", name: "Cable Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "hanging_leg_raise", name: "Hanging Leg Raise", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "machine_crunch", name: "Machine Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "cable_woodchop", name: "Cable Woodchop", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_pallof_press", name: "Band Pallof Press", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "wrist_curl", name: "Wrist Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "reverse_curl", name: "Reverse Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "farmer_walk", name: "Farmer's Walk", pattern: .carry, primary: .forearms, synergists: [.back], isCompound: true, equipment: .dumbbell),
    Exercise(id: "decline_bench_press", name: "Decline Barbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "wide_grip_bench_press", name: "Wide-Grip Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "pause_bench_press", name: "Paused Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "tempo_bench_press", name: "Tempo Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "spoto_press", name: "Spoto Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "barbell_floor_press", name: "Barbell Floor Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "flat_db_bench_press", name: "Flat Dumbbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "decline_db_press", name: "Decline Dumbbell Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "db_floor_press", name: "Dumbbell Floor Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "single_arm_db_bench_press", name: "Single-Arm Dumbbell Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "db_squeeze_press", name: "Dumbbell Squeeze Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "smith_bench_press", name: "Smith Machine Bench Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "smith_incline_bench_press", name: "Smith Machine Incline Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "machine_decline_press", name: "Machine Decline Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "machine_assisted_dip", name: "Machine-Assisted Dip", pattern: .verticalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "single_arm_cable_press", name: "Single-Arm Cable Chest Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .cable),
    Exercise(id: "band_chest_press", name: "Band Chest Press", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bands),
    Exercise(id: "band_chest_fly", name: "Band Chest Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "incline_cable_fly", name: "Incline Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "decline_cable_fly", name: "Decline Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "low_to_high_cable_fly", name: "Low-to-High Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "high_to_low_cable_fly", name: "High-to-Low Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "single_arm_cable_fly", name: "Single-Arm Cable Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "incline_db_fly", name: "Incline Dumbbell Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "decline_db_fly", name: "Decline Dumbbell Fly", pattern: .horizontalPush, primary: .chest, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "weighted_chest_dip", name: "Weighted Chest Dip", pattern: .verticalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "ring_dip", name: "Ring Dip", pattern: .verticalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "decline_push_up", name: "Decline Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "incline_push_up", name: "Incline Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "wide_push_up", name: "Wide Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "weighted_push_up", name: "Weighted Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "archer_push_up", name: "Archer Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "push_up_plus", name: "Push-Up Plus", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "band_push_up", name: "Band-Resisted Push-Up", pattern: .horizontalPush, primary: .chest, synergists: [.triceps, .frontDelts], isCompound: true, equipment: .bands),
    Exercise(id: "wide_grip_lat_pulldown", name: "Wide-Grip Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "close_grip_lat_pulldown", name: "Close-Grip Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "neutral_grip_lat_pulldown", name: "Neutral-Grip Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "single_arm_lat_pulldown", name: "Single-Arm Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "reverse_grip_pulldown", name: "Reverse-Grip Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .cable),
    Exercise(id: "band_lat_pulldown", name: "Band Lat Pulldown", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bands),
    Exercise(id: "band_assisted_pull_up", name: "Band-Assisted Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bands),
    Exercise(id: "machine_assisted_pull_up", name: "Machine-Assisted Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .machine),
    Exercise(id: "weighted_pull_up", name: "Weighted Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "wide_grip_pull_up", name: "Wide-Grip Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "close_grip_pull_up", name: "Close-Grip Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "neutral_grip_pull_up", name: "Neutral-Grip Pull-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "weighted_chin_up", name: "Weighted Chin-Up", pattern: .verticalPull, primary: .back, synergists: [.biceps], isCompound: true, equipment: .bodyweight),
    Exercise(id: "scapular_pull_up", name: "Scapular Pull-Up", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "wide_grip_seated_row", name: "Wide-Grip Seated Cable Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .cable),
    Exercise(id: "close_grip_seated_row", name: "Close-Grip Seated Cable Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .cable),
    Exercise(id: "t_bar_row", name: "T-Bar Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "single_arm_t_bar_row", name: "Single-Arm T-Bar Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "meadows_row", name: "Meadows Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "seal_row", name: "Seal Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "yates_row", name: "Yates Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "wide_grip_bent_row", name: "Wide-Grip Barbell Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "underhand_bent_row", name: "Underhand Barbell Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "smith_row", name: "Smith Machine Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "machine_high_row", name: "Machine High Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "single_arm_machine_row", name: "Single-Arm Machine Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .machine),
    Exercise(id: "incline_db_row", name: "Incline Dumbbell Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "bent_over_db_row", name: "Bent-Over Dumbbell Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "kroc_row", name: "Kroc Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "renegade_row", name: "Renegade Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "wide_grip_inverted_row", name: "Wide-Grip Inverted Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "close_grip_inverted_row", name: "Close-Grip Inverted Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "underhand_inverted_row", name: "Underhand Inverted Row", pattern: .horizontalPull, primary: .back, synergists: [.biceps, .rearDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "barbell_pullover", name: "Barbell Pullover", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "db_pullover", name: "Dumbbell Pullover", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "machine_pullover", name: "Machine Pullover", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "straight_arm_band_pulldown", name: "Straight-Arm Band Pulldown", pattern: .verticalPull, primary: .back, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "barbell_shrug", name: "Barbell Shrug", pattern: .isolation, primary: .back, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "db_shrug", name: "Dumbbell Shrug", pattern: .isolation, primary: .back, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_shrug", name: "Cable Shrug", pattern: .isolation, primary: .back, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "pause_squat", name: "Paused Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "tempo_squat", name: "Tempo Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "box_squat", name: "Box Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "safety_bar_squat", name: "Safety Bar Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "zercher_squat", name: "Zercher Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "overhead_squat", name: "Overhead Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "landmine_squat", name: "Landmine Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "smith_squat", name: "Smith Machine Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "belt_squat", name: "Belt Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "pendulum_squat", name: "Pendulum Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "barbell_hack_squat", name: "Barbell Hack Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "db_squat", name: "Dumbbell Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "kb_front_squat", name: "Kettlebell Front Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "band_squat", name: "Band Squat", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .bands),
    Exercise(id: "wide_stance_leg_press", name: "Wide-Stance Leg Press", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "narrow_stance_leg_press", name: "Narrow-Stance Leg Press", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "single_leg_press", name: "Single-Leg Leg Press", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .machine),
    Exercise(id: "single_leg_leg_extension", name: "Single-Leg Extension", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "spanish_squat", name: "Spanish Squat", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "wall_sit", name: "Wall Sit", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "terminal_knee_extension", name: "Terminal Knee Extension", pattern: .isolation, primary: .quads, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "squat_jump", name: "Squat Jump", pattern: .squat, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .bodyweight),
    Exercise(id: "barbell_split_squat", name: "Barbell Split Squat", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "db_split_squat", name: "Dumbbell Split Squat", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "barbell_bulgarian_split_squat", name: "Barbell Bulgarian Split Squat", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "walking_lunge", name: "Walking Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "db_reverse_lunge", name: "Dumbbell Reverse Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "barbell_reverse_lunge", name: "Barbell Reverse Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "landmine_reverse_lunge", name: "Landmine Reverse Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .barbell),
    Exercise(id: "db_forward_lunge", name: "Dumbbell Forward Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "lateral_lunge", name: "Lateral Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "curtsy_lunge", name: "Curtsy Lunge", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "db_step_up", name: "Dumbbell Step-Up", pattern: .lunge, primary: .quads, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "trap_bar_deadlift", name: "Trap Bar Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "deficit_deadlift", name: "Deficit Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "paused_deadlift", name: "Paused Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "stiff_leg_deadlift", name: "Stiff-Leg Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "snatch_grip_deadlift", name: "Snatch-Grip Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "deficit_sumo_deadlift", name: "Deficit Sumo Deadlift", pattern: .hinge, primary: .glutes, synergists: [.hamstrings, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "rack_pull", name: "Rack Pull", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "db_romanian_deadlift", name: "Dumbbell Romanian Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "kb_romanian_deadlift", name: "Kettlebell Romanian Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .dumbbell),
    Exercise(id: "kb_deadlift", name: "Kettlebell Deadlift", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .dumbbell),
    Exercise(id: "seated_good_morning", name: "Seated Good Morning", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "single_leg_good_morning", name: "Single-Leg Good Morning", pattern: .hinge, primary: .hamstrings, synergists: [.glutes, .back], isCompound: true, equipment: .barbell),
    Exercise(id: "band_good_morning", name: "Band Good Morning", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .bands),
    Exercise(id: "back_extension", name: "Back Extension", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .bodyweight),
    Exercise(id: "single_leg_back_extension", name: "Single-Leg Back Extension", pattern: .hinge, primary: .hamstrings, synergists: [.glutes], isCompound: true, equipment: .bodyweight),
    Exercise(id: "single_leg_leg_curl", name: "Single-Leg Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "band_leg_curl", name: "Band Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "stability_ball_leg_curl", name: "Stability Ball Leg Curl", pattern: .isolation, primary: .hamstrings, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "barbell_glute_bridge", name: "Barbell Glute Bridge", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .barbell),
    Exercise(id: "single_leg_glute_bridge", name: "Single-Leg Glute Bridge", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .bodyweight),
    Exercise(id: "single_leg_hip_thrust", name: "Single-Leg Hip Thrust", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .bodyweight),
    Exercise(id: "band_hip_thrust", name: "Band Hip Thrust", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .bands),
    Exercise(id: "smith_hip_thrust", name: "Smith Machine Hip Thrust", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .machine),
    Exercise(id: "reverse_hyperextension", name: "Reverse Hyperextension", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .machine),
    Exercise(id: "kb_swing", name: "Kettlebell Swing", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .dumbbell),
    Exercise(id: "glute_bridge_march", name: "Glute Bridge March", pattern: .hinge, primary: .glutes, synergists: [.hamstrings], isCompound: true, equipment: .bodyweight),
    Exercise(id: "band_glute_kickback", name: "Band Glute Kickback", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "machine_glute_kickback", name: "Machine Glute Kickback", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "band_clamshell", name: "Band Clamshell", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "band_hip_abduction", name: "Band Hip Abduction", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "fire_hydrant", name: "Fire Hydrant", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "machine_hip_abduction", name: "Machine Hip Abduction", pattern: .isolation, primary: .glutes, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "push_press", name: "Push Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "z_press", name: "Z Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "seated_barbell_press", name: "Seated Barbell Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "standing_db_press", name: "Standing Dumbbell Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "single_arm_db_press", name: "Single-Arm Dumbbell Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .dumbbell),
    Exercise(id: "single_arm_landmine_press", name: "Single-Arm Landmine Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .chest], isCompound: true, equipment: .barbell),
    Exercise(id: "smith_overhead_press", name: "Smith Machine Overhead Press", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .machine),
    Exercise(id: "pike_push_up", name: "Pike Push-Up", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "handstand_push_up", name: "Handstand Push-Up", pattern: .verticalPush, primary: .frontDelts, synergists: [.triceps, .sideDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "db_front_raise", name: "Dumbbell Front Raise", pattern: .isolation, primary: .frontDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_front_raise", name: "Cable Front Raise", pattern: .isolation, primary: .frontDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_front_raise", name: "Band Front Raise", pattern: .isolation, primary: .frontDelts, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "db_overhead_carry", name: "Overhead Dumbbell Carry", pattern: .carry, primary: .frontDelts, synergists: [.triceps], isCompound: true, equipment: .dumbbell),
    Exercise(id: "barbell_upright_row", name: "Barbell Upright Row", pattern: .verticalPull, primary: .sideDelts, synergists: [.back, .biceps], isCompound: true, equipment: .barbell),
    Exercise(id: "db_upright_row", name: "Dumbbell Upright Row", pattern: .verticalPull, primary: .sideDelts, synergists: [.back, .biceps], isCompound: true, equipment: .dumbbell),
    Exercise(id: "cable_upright_row", name: "Cable Upright Row", pattern: .verticalPull, primary: .sideDelts, synergists: [.back, .biceps], isCompound: true, equipment: .cable),
    Exercise(id: "wide_grip_upright_row", name: "Wide-Grip Barbell Upright Row", pattern: .verticalPull, primary: .sideDelts, synergists: [.back, .biceps], isCompound: true, equipment: .barbell),
    Exercise(id: "single_arm_cable_lateral_raise", name: "Single-Arm Cable Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "seated_db_lateral_raise", name: "Seated Dumbbell Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "incline_db_lateral_raise", name: "Incline Dumbbell Lateral Raise", pattern: .isolation, primary: .sideDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "incline_rear_delt_fly", name: "Incline Rear Delt Fly", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_rear_delt_fly", name: "Cable Rear Delt Fly", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_face_pull", name: "Band Face Pull", pattern: .horizontalPull, primary: .rearDelts, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "diamond_push_up", name: "Diamond Push-Up", pattern: .horizontalPush, primary: .triceps, synergists: [.chest, .frontDelts], isCompound: true, equipment: .bodyweight),
    Exercise(id: "close_grip_incline_press", name: "Close-Grip Incline Press", pattern: .horizontalPush, primary: .triceps, synergists: [.chest, .frontDelts], isCompound: true, equipment: .barbell),
    Exercise(id: "smith_close_grip_press", name: "Smith Machine Close-Grip Press", pattern: .horizontalPush, primary: .triceps, synergists: [.chest, .frontDelts], isCompound: true, equipment: .machine),
    Exercise(id: "bench_dip", name: "Bench Dip", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "jm_press", name: "JM Press", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "tate_press", name: "Tate Press", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "rope_overhead_extension", name: "Cable Rope Overhead Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "overhead_barbell_extension", name: "Overhead Barbell Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "single_arm_overhead_db_extension", name: "Single-Arm Overhead Dumbbell Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "single_arm_tricep_pushdown", name: "Single-Arm Cable Pushdown", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "reverse_grip_pushdown", name: "Reverse-Grip Pushdown", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "db_kickback", name: "Dumbbell Kickback", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_tricep_kickback", name: "Cable Kickback", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "band_tricep_pushdown", name: "Band Pushdown", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "band_overhead_triceps_extension", name: "Band Overhead Triceps Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "machine_triceps_extension", name: "Machine Triceps Extension", pattern: .isolation, primary: .triceps, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "ez_bar_curl", name: "EZ-Bar Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "wide_grip_barbell_curl", name: "Wide-Grip Barbell Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "drag_curl", name: "Drag Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "ez_bar_preacher_curl", name: "EZ-Bar Preacher Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "machine_preacher_curl", name: "Machine Preacher Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "concentration_curl", name: "Concentration Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "seated_db_curl", name: "Seated Dumbbell Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "seated_hammer_curl", name: "Seated Hammer Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "incline_hammer_curl", name: "Incline Hammer Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "cable_hammer_curl", name: "Cable Hammer Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "single_arm_cable_curl", name: "Single-Arm Cable Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "incline_cable_curl", name: "Incline Cable Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "machine_biceps_curl", name: "Machine Biceps Curl", pattern: .isolation, primary: .biceps, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "barbell_wrist_curl", name: "Barbell Wrist Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "behind_back_wrist_curl", name: "Behind-the-Back Wrist Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "reverse_barbell_curl", name: "Reverse Barbell Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "reverse_cable_curl", name: "Reverse Cable Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "zottman_curl", name: "Zottman Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "reverse_wrist_curl", name: "Reverse Wrist Curl", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .dumbbell),
    Exercise(id: "dead_hang", name: "Dead Hang", pattern: .isolation, primary: .forearms, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "suitcase_carry", name: "Suitcase Carry", pattern: .carry, primary: .abs, synergists: [.forearms, .back], isCompound: true, equipment: .dumbbell),
    Exercise(id: "trap_bar_carry", name: "Trap Bar Carry", pattern: .carry, primary: .forearms, synergists: [.back], isCompound: true, equipment: .barbell),
    Exercise(id: "leg_press_calf_raise", name: "Leg Press Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "smith_calf_raise", name: "Smith Machine Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "barbell_calf_raise", name: "Barbell Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .barbell),
    Exercise(id: "single_leg_calf_raise", name: "Single-Leg Standing Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "bodyweight_calf_raise", name: "Bodyweight Standing Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "band_calf_raise", name: "Band Calf Raise", pattern: .isolation, primary: .calves, synergists: [], isCompound: false, equipment: .bands),
    Exercise(id: "plank", name: "Plank", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "side_plank", name: "Side Plank", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "plank_shoulder_tap", name: "Plank Shoulder Tap", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "copenhagen_plank", name: "Copenhagen Plank", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "dead_bug", name: "Dead Bug", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "bird_dog", name: "Bird Dog", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "ab_wheel_rollout", name: "Ab Wheel Rollout", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "dragon_flag", name: "Dragon Flag", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "hanging_knee_raise", name: "Hanging Knee Raise", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "weighted_hanging_leg_raise", name: "Weighted Hanging Leg Raise", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "toes_to_bar", name: "Toes-to-Bar", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "lying_leg_raise", name: "Lying Leg Raise", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "flutter_kick", name: "Flutter Kick", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "captain_chair_leg_raise", name: "Captain's Chair Leg Raise", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "reverse_crunch", name: "Reverse Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "crunch", name: "Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "sit_up", name: "Sit-Up", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "decline_sit_up", name: "Decline Sit-Up", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "v_up", name: "V-Up", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "bicycle_crunch", name: "Bicycle Crunch", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "russian_twist", name: "Russian Twist", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "mountain_climber", name: "Mountain Climber", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
    Exercise(id: "ghd_sit_up", name: "GHD Sit-Up", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .machine),
    Exercise(id: "cable_pallof_press", name: "Cable Pallof Press", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .cable),
    Exercise(id: "windshield_wiper", name: "Windshield Wiper", pattern: .core, primary: .abs, synergists: [], isCompound: false, equipment: .bodyweight),
  ]

  public static var custom: [Exercise] = []
  public static var everything: [Exercise] { all + custom }

  public static func find(_ id: String) -> Exercise? {
    everything.first { $0.id == id }
  }

  public static func matching(equipment: Set<Equipment>) -> [Exercise] {
    everything.filter { equipment.contains($0.equipment) }
  }

  /// Swap candidates for `exercise`: same pattern and primary muscle first,
  /// then same pattern. Excludes the exercise itself and any exercise flagged
  /// for the given injuries, and respects available equipment.
  public static func replacements(for exercise: Exercise, equipment: Set<Equipment>, injuries: Set<InjuryFlag>, limit: Int = 6) -> [Exercise] {
    func flagged(_ candidate: Exercise) -> Bool {
      Substitution.replacement(for: candidate.id, flags: injuries) != nil
    }
    let sameMuscle = everything.filter {
      $0.id != exercise.id
        && $0.pattern == exercise.pattern
        && $0.primary == exercise.primary
        && equipment.contains($0.equipment)
        && !flagged($0)
    }
    let samePattern = everything.filter {
      $0.id != exercise.id
        && $0.pattern == exercise.pattern
        && $0.primary != exercise.primary
        && equipment.contains($0.equipment)
        && !flagged($0)
    }
    return Array((sameMuscle + samePattern).prefix(limit))
  }
}
