// Reads knowledge/*.md → src/knowledge.generated.ts (Workers have no filesystem).
// Run via `pnpm gen` (Node 24 strips types natively; no deps).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const files = readdirSync(join(root, "knowledge"))
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((f) => ({ file: f, text: readFileSync(join(root, "knowledge", f), "utf8") }));

const out = `// Generated by scripts/gen-knowledge.ts — do not edit.
export const KNOWLEDGE: { file: string; text: string }[] = ${JSON.stringify(files, null, 2)};
`;
writeFileSync(join(root, "src", "knowledge.generated.ts"), out);
console.log(`knowledge.generated.ts: ${files.length} files`);
