name = "forge-site"
compatibility_date = "2025-09-01"
routes = [
  { pattern = "regulift.app", custom_domain = true },
  { pattern = "www.regulift.app", custom_domain = true }
]

[assets]
directory = "."
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
